theme-name: The One
theme-name-lowercase: theone
theme-filename: TheOne
theme-folder-name: the-one-theme
theme-uuid: 8ebe1e30-b4ff-4417-8b6c-f4bbace51f28
version: 1.0.0
github-url: benniemosher/the-one-theme
copyright: '2015'
license-type: MIT
license-url: http://benniemosher.mit-license.org
author-name: Bennie Mosher
author-email: <benniemosher@gmail.com>
background-color: '#272B33'
comment-color: '#5b626f'
current-line-color: '#2c323d'
foreground-color: '#abb2c0'
selection-color: '#3e4451'
caret-color: '#528bff'
invisibles-color: '#abb2bf'
find-highlight-color: '#abb2bf'
find-highlight-foreground-color: '#528bff'
selection-border-color: '#3e4451'
active-guide-color: '#0a3a61'
string-foreground-color: '#abb2bf'
constant-numeric-color: '#d19a66'
contant-language-color: '#d19a66'
user-defined-constant-color: '#d19a66'
variable-font-style: ''
rubys-@variable-font-style: ''
rubys-@variable-color: '#be5046'
string-interpolation-font-style: ''
string-interpolation-color: '#98c379'
keyword-color: '#c678dd'
storage-font-style: ''
storage-color: '#e06c75'
storage-type-font-style: 'italic'
storage-type-color: '#56b6c2'
class-name-font-style: 'underline'
class-name-color: '#e5c07b'
inherited-class-font-style: 'italic underline'
inherited-class-color: '#98c379'
funtion-name-font-style: ''
funtion-name-color: '#61afef'
function-argument-font-style: 'italic'
function-argument-color: '#abb2bf'
tag-name-font-style: ''
tag-name-color: '#e06c75'
tag-attribute-font-style: ''
tag-attribute-color: '#98c379'
library-function-font-style: ''
library-function-color: '#61afef'
library-constant-font-style: ''
library-constant-color: '#56b6c2'
library-class-type-font-style: 'italic'
library-class-type-color: '#56b6c2'
